from django.utils.translation import ugettext_lazy as _

PAYMENT_TYPE_BANK_CARD = 1
PAYMENT_TYPE_CASH_ON_DELIVERY = 2

PAYMENT_TYPES = (
    (PAYMENT_TYPE_BANK_CARD, _("Bank card")),
    (PAYMENT_TYPE_CASH_ON_DELIVERY, _("Cash on delivery")),
)

DELIVERY_COMPANY_NOVA_POSHTA = 1
DELIVERY_COMPANY_UKRPOSHTA = 2

DELIVERY_COMPANIES = (
    (DELIVERY_COMPANY_NOVA_POSHTA, _("Nova Poshta")),
    (DELIVERY_COMPANY_UKRPOSHTA, _("UkrPoshta")),
)

DELIVERY_COMPANY_BRANCH = 1
DELIVERY_COMPANY_CURRIER = 2

DELIVERY_TYPES = (
    (DELIVERY_COMPANY_BRANCH, _("Branch")),
    (DELIVERY_COMPANY_CURRIER, _("Currier")),
)
