# Generated by Django 3.0.8 on 2020-09-01 21:33

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
