# Generated by Django 3.0.8 on 2020-10-18 20:19

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations
from django.db import models

import product.models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_configuration_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariantImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("image", models.ImageField(upload_to=product.models.upload_to)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="product.ProductVariant",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
