# Generated by Django 3.0.8 on 2020-09-14 10:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0002_configuration_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "payment_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Bank card"), (2, "Cash on delivery")]
                    ),
                ),
                (
                    "delivery_company",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Nova Poshta"), (2, "UkrPoshta")]
                    ),
                ),
                (
                    "delivery_type",
                    models.PositiveSmallIntegerField(choices=[(1, "Branch"), (2, "Currier")]),
                ),
                ("branch", models.CharField(max_length=256)),
                ("region", models.CharField(max_length=256)),
                ("city", models.CharField(max_length=256)),
                ("comment", models.TextField(blank=True, null=True)),
                ("dont_call", models.BooleanField(default=False)),
                ("status", models.PositiveSmallIntegerField(choices=[(1, "New")], default=1)),
            ],
            options={"verbose_name": "Order", "verbose_name_plural": "Orders",},
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("first_name", models.CharField(max_length=256)),
                ("second_name", models.CharField(max_length=256)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={"verbose_name": "Recipient", "verbose_name_plural": "Recipients",},
        ),
        migrations.CreateModel(
            name="ProductVariantOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "qty",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="order.Order"
                    ),
                ),
                (
                    "product_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="product.ProductVariant"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="order",
            name="details",
            field=models.ManyToManyField(
                related_name="details",
                through="order.ProductVariantOrder",
                to="product.ProductVariant",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="order.Recipient"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="second_recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="secondary_orders",
                to="order.Recipient",
            ),
        ),
    ]
