# Generated by Django 3.0.8 on 2020-09-14 08:46

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("first_name", models.CharField(max_length=256)),
                ("second_name", models.CharField(max_length=256)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "payment_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Bank card"), (2, "Cash on delivery")]
                    ),
                ),
                (
                    "delivery_company",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Nova Poshta"), (2, "UkrPoshta")]
                    ),
                ),
                (
                    "delivery_type",
                    models.PositiveSmallIntegerField(choices=[(1, "Branch"), (2, "Currier")]),
                ),
                ("region", models.CharField(max_length=256)),
                ("city", models.CharField(max_length=256)),
                ("branch", models.CharField(max_length=256)),
                ("comment", models.TextField(blank=True, null=True,)),
                ("dont_call", models.BooleanField(default=False)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="order.Recipient"
                    ),
                ),
                (
                    "second_recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secondary_orders",
                        to="order.Recipient",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
