# Generated by Django 3.0.8 on 2020-10-06 21:28

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_auto_20201005_2208"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="order.Recipient",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "New"),
                    (2, "Didn't call"),
                    (3, "Approved"),
                    (4, "Wait for payment"),
                    (5, "Completed"),
                    (6, "Paid"),
                    (7, "Canceled"),
                    (8, "Returned"),
                ],
                default=1,
            ),
        ),
    ]
