# Generated by Django 3.0.8 on 2020-11-06 08:04

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_auto_20201006_2128"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "notification_type",
                    models.PositiveSmallIntegerField(choices=[(1, "SMS")], default=1),
                ),
                ("text", models.TextField()),
                ("is_sent", models.BooleanField(default=False)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="order.Order",
                    ),
                ),
            ],
            options={"verbose_name": "Notification", "verbose_name_plural": "Notifications",},
        ),
    ]
