# Generated by Django 3.0.8 on 2021-03-01 21:58

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="campaign_id",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_delivered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="ttn",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.PositiveSmallIntegerField(choices=[(1, "SMS"), (2, "Email")], default=1),
        ),
    ]
